# Generated by Django 4.2 on 2024-01-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='ffffff', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('generation', models.SmallIntegerField()),
                ('hp', models.SmallIntegerField()),
                ('atk', models.SmallIntegerField()),
                ('dfn', models.SmallIntegerField()),
                ('spatk', models.SmallIntegerField()),
                ('spdef', models.SmallIntegerField()),
                ('spd', models.SmallIntegerField()),
                ('types', models.ManyToManyField(to='pokedex.types')),
            ],
        ),
    ]
