# Generated by Django 4.2 on 2024-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='generation',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.CharField(blank=True),
        ),
    ]
