# Generated by Django 4.2 on 2024-01-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_remove_pokemon_generation_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
